version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test-app:
    executor:
      name: node/default
    docker:
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run: npm install
      - run: npm start &
      - run: npm test
workflows:
  test-app:
    jobs:
      - test-app
