version: 2.1
jobs:
  test-app:
    docker:
      - image: circleci/mongo:latest
      - image: circleci/node:11.3
    steps:
      - checkout
      - run: npm install
      - run: npm start &
      - run: npm test
workflows:
  test-app:
    jobs:
      - test-app
